[workspace]
default-members = ["ant_cluster_graphics"]
members = [
    "ant_cluster",
    "ant_cluster_data",
    "ant_cluster_graphics",
    "ant_cluster_async",
    "data_retrieve",
    "agent",
    "graphics_engine",
]
