[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
map = {path="../map"}
agent = {path="../agent"}
data_retrieve = {path="../data_retrieve"}